In [9]:
#1.Write a python program to display all the header tags from wikipedia.org.
from urllib.request import urlopen
from bs4 import BeautifulSoup
import requests
page = requests.get('https://en.wikipedia.org/wiki/Main_Page')
page

In [10]:

html = urlopen('https://en.wikipedia.org/wiki/Main_Page')
bs = BeautifulSoup(html, "html.parser")
titles = bs.find_all(['h1', 'h2','h3','h4','h5','h6'])
print('List all the header tags :', *titles, sep='\n\n')

List all the header tags :

<h1 class="firstHeading mw-first-heading" id="firstHeading" style="display: none">Main Page</h1>

<h1><span class="mw-headline" id="Welcome_to_Wikipedia">Welcome to <a href="/wiki/Wikipedia" title="Wikipedia">Wikipedia</a></span></h1>

<h2 class="mp-h2" id="mp-tfa-h2"><span id="From_today.27s_featured_article"></span><span class="mw-headline" id="From_today's_featured_article">From today's featured article</span></h2>

<h2 class="mp-h2" id="mp-dyk-h2"><span class="mw-headline" id="Did_you_know_...">Did you know ...</span></h2>

<h2 class="mp-h2" id="mp-itn-h2"><span class="mw-headline" id="In_the_news">In the news</span></h2>

<h2 class="mp-h2" id="mp-otd-h2"><span class="mw-headline" id="On_this_day">On this day</span></h2>

<h2 class="mp-h2" id="mp-tfl-h2"><span id="From_today.27s_featured_list"></span><span class="mw-headline" id="From_today's_featured_list">From today's featured list</span></h2>

<h2 class="mp-h2" id="mp-tfp-h2"><span id="Today.27s_featured_picture"></span><span class="mw-headline" id="Today's_featured_picture">Today's featured picture</span></h2>

<h2 class="mp-h2" id="mp-other"><span class="mw-headline" id="Other_areas_of_Wikipedia">Other areas of Wikipedia</span></h2>

<h2 class="mp-h2" id="mp-sister"><span id="Wikipedia.27s_sister_projects"></span><span class="mw-headline" id="Wikipedia's_sister_projects">Wikipedia's sister projects</span></h2>

<h2 class="mp-h2" id="mp-lang"><span class="mw-headline" id="Wikipedia_languages">Wikipedia languages</span></h2>

<h2>Navigation menu</h2>

<h3 class="vector-menu-heading" id="p-personal-label">
<span class="vector-menu-heading-label">Personal tools</span>
</h3>

<h3 class="vector-menu-heading" id="p-namespaces-label">
<span class="vector-menu-heading-label">Namespaces</span>
</h3>

<h3 class="vector-menu-heading" id="p-views-label">
<span class="vector-menu-heading-label">Views</span>
</h3>

<h3>
<label for="searchInput">Search</label>
</h3>

<h3 class="vector-menu-heading" id="p-navigation-label">
<span class="vector-menu-heading-label">Navigation</span>
</h3>

<h3 class="vector-menu-heading" id="p-interaction-label">
<span class="vector-menu-heading-label">Contribute</span>
</h3>

<h3 class="vector-menu-heading" id="p-tb-label">
<span class="vector-menu-heading-label">Tools</span>
</h3>

<h3 class="vector-menu-heading" id="p-coll-print_export-label">
<span class="vector-menu-heading-label">Print/export</span>
</h3>

<h3 class="vector-menu-heading" id="p-wikibase-otherprojects-label">
<span class="vector-menu-heading-label">In other projects</span>
</h3>

<h3 class="vector-menu-heading" id="p-lang-label">
<span class="vector-menu-heading-label">Languages</span>
</h3>

In [17]:
title = []
for i in bs.find_all('span', class_="mw-headline"):
    title.append(i.text)
title

['Welcome to Wikipedia',
 "From today's featured article",
 'Did you know\xa0...',
 'In the news',
 'On this day',
 "From today's featured list",
 "Today's featured picture",
 'Other areas of Wikipedia',
 "Wikipedia's sister projects",
 'Wikipedia languages']

In [59]:
# 2) Write a python program to display IMDB’s Top rated 100 movies’ data (i.e. name, rating, year of release)
#and make data frame.

from bs4 import BeautifulSoup
import requests
import re
import pandas as pd
page = requests.get('http://www.imdb.com/chart/top')
page

In [60]:
# Downloading imdb top 100 movie's data
url = 'http://www.imdb.com/chart/top'
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")
movies = soup.select('td.titleColumn')
crew = [a.attrs.get('title') for a in soup.select('td.titleColumn a')]
ratings = [b.attrs.get('data-value')
           for b in soup.select('td.posterColumn span[name=ir]')]

In [61]:
# create a empty list for storing
# movie information
list = []

# Iterating over movies to extract
# each movie's details
for index in range(0, len(movies)):
# Separating movie into: 'place',
# 'title', 'year'
    movie_string = movies[index].get_text()
    movie = (' '.join(movie_string.split()).replace('.', ''))
    movie_title = movie[len(str(index))+1:-7]
    year = re.search('\((.*?)\)', movie_string).group(1)
    place = movie[:len(str(index))-(len(movie))]
    data = {"place": place,
            "movie_title": movie_title,
            "rating": ratings[index],
            "year": year,
            "star_cast": crew[index],
           }
    list.append(data)

In [62]:
for movie in list:
    print(movie['place'], '-', movie['movie_title'], '('+movie['year'] +
          ') -', 'Starring:', movie['star_cast'], movie['rating'])
#saving the list as dataframe
#then converting into .csv file
df = pd.DataFrame(list)
df.to_csv('imdb_top_100_movies.csv',index=False)

1 - The Shawshank Redemption (1994) - Starring: Frank Darabont (dir.), Tim Robbins, Morgan Freeman 9.233944969314647
2 - The Godfather (1972) - Starring: Francis Ford Coppola (dir.), Marlon Brando, Al Pacino 9.156028704679505
3 - The Dark Knight (2008) - Starring: Christopher Nolan (dir.), Christian Bale, Heath Ledger 8.985687692652556
4 - The Godfather Part II (1974) - Starring: Francis Ford Coppola (dir.), Al Pacino, Robert De Niro 8.984186930445007
5 - 12 Angry Men (1957) - Starring: Sidney Lumet (dir.), Henry Fonda, Lee J. Cobb 8.947801070232531
6 - Schindler's List (1993) - Starring: Steven Spielberg (dir.), Liam Neeson, Ralph Fiennes 8.935338565587331
7 - The Lord of the Rings: The Return of the King (2003) - Starring: Peter Jackson (dir.), Elijah Wood, Viggo Mortensen 8.921336761776189
8 - Pulp Fiction (1994) - Starring: Quentin Tarantino (dir.), John Travolta, Uma Thurman 8.85064422942527
9 - The Lord of the Rings: The Fellowship of the Ring (2001) - Starring: Peter Jackson (dir.), Elijah Wood, Ian McKellen 8.803755641902287
1 -  Il buono, il brutto, il cattivo (1966) - Starring: Sergio Leone (dir.), Clint Eastwood, Eli Wallach 8.793547799270932
11 - Forrest Gump (1994) - Starring: Robert Zemeckis (dir.), Tom Hanks, Robin Wright 8.767373258724499
12 - Fight Club (1999) - Starring: David Fincher (dir.), Brad Pitt, Edward Norton 8.749843980029404
13 - Inception (2010) - Starring: Christopher Nolan (dir.), Leonardo DiCaprio, Joseph Gordon-Levitt 8.732927674664722
14 - The Lord of the Rings: The Two Towers (2002) - Starring: Peter Jackson (dir.), Elijah Wood, Ian McKellen 8.728006668103765
15 - The Empire Strikes Back (1980) - Starring: Irvin Kershner (dir.), Mark Hamill, Harrison Ford 8.701693024418049
16 - The Matrix (1999) - Starring: Lana Wachowski (dir.), Keanu Reeves, Laurence Fishburne 8.670938416499565
17 - Goodfellas (1990) - Starring: Martin Scorsese (dir.), Robert De Niro, Ray Liotta 8.651688798613113
18 - One Flew Over the Cuckoo's Nest (1975) - Starring: Milos Forman (dir.), Jack Nicholson, Louise Fletcher 8.641075525839828
19 - Se7en (1995) - Starring: David Fincher (dir.), Morgan Freeman, Brad Pitt 8.604101421838783
20 - Shichinin no samurai (1954) - Starring: Akira Kurosawa (dir.), Toshirô Mifune, Takashi Shimura 8.598837932260698
21 - It's a Wonderful Life (1946) - Starring: Frank Capra (dir.), James Stewart, Donna Reed 8.596905215376802
22 - The Silence of the Lambs (1991) - Starring: Jonathan Demme (dir.), Jodie Foster, Anthony Hopkins 8.58802764315417
23 - Cidade de Deus (2002) - Starring: Fernando Meirelles (dir.), Alexandre Rodrigues, Leandro Firmino 8.57887434891388
24 - Saving Private Ryan (1998) - Starring: Steven Spielberg (dir.), Tom Hanks, Matt Damon 8.577818092610075
25 - La vita è bella (1997) - Starring: Roberto Benigni (dir.), Roberto Benigni, Nicoletta Braschi 8.566084857425384
26 - The Green Mile (1999) - Starring: Frank Darabont (dir.), Tom Hanks, Michael Clarke Duncan 8.559855520072217
27 - Interstellar (2014) - Starring: Christopher Nolan (dir.), Matthew McConaughey, Anne Hathaway 8.555921654811245
28 - Star Wars (1977) - Starring: George Lucas (dir.), Mark Hamill, Harrison Ford 8.554073030617365
29 - Terminator 2: Judgment Day (1991) - Starring: James Cameron (dir.), Arnold Schwarzenegger, Linda Hamilton 8.535167031801643
30 - Back to the Future (1985) - Starring: Robert Zemeckis (dir.), Michael J. Fox, Christopher Lloyd 8.518150296482254
31 - Sen to Chihiro no kamikakushi (2001) - Starring: Hayao Miyazaki (dir.), Daveigh Chase, Suzanne Pleshette 8.515349774783191
32 - Psycho (1960) - Starring: Alfred Hitchcock (dir.), Anthony Perkins, Janet Leigh 8.508606200089801
33 - The Pianist (2002) - Starring: Roman Polanski (dir.), Adrien Brody, Thomas Kretschmann 8.504549807085573
34 - Léon (1994) - Starring: Luc Besson (dir.), Jean Reno, Gary Oldman 8.500409102460338
35 - Gisaengchung (2019) - Starring: Bong Joon Ho (dir.), Song Kang-ho, Sun-kyun Lee 8.495745999089872
36 - The Lion King (1994) - Starring: Roger Allers (dir.), Matthew Broderick, Jeremy Irons 8.48840379460557
37 - Gladiator (2000) - Starring: Ridley Scott (dir.), Russell Crowe, Joaquin Phoenix 8.485423828914366
38 - American History X (1998) - Starring: Tony Kaye (dir.), Edward Norton, Edward Furlong 8.484366983643422
39 - The Usual Suspects (1995) - Starring: Bryan Singer (dir.), Kevin Spacey, Gabriel Byrne 8.476217332062747
40 - The Departed (2006) - Starring: Martin Scorsese (dir.), Leonardo DiCaprio, Matt Damon 8.475119970665846
41 - The Prestige (2006) - Starring: Christopher Nolan (dir.), Christian Bale, Hugh Jackman 8.46797870799699
42 - Casablanca (1942) - Starring: Michael Curtiz (dir.), Humphrey Bogart, Ingrid Bergman 8.465490431870968
43 - Top Gun: Maverick (2022) - Starring: Joseph Kosinski (dir.), Tom Cruise, Jennifer Connelly 8.462537545035026
44 - Whiplash (2014) - Starring: Damien Chazelle (dir.), Miles Teller, J.K. Simmons 8.460525566962493
45 - The Intouchables (2011) - Starring: Olivier Nakache (dir.), François Cluzet, Omar Sy 8.453718611600312
46 - Modern Times (1936) - Starring: Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard 8.44967011390304
47 - Seppuku (1962) - Starring: Masaki Kobayashi (dir.), Tatsuya Nakadai, Akira Ishihama 8.448653397089343
48 - Hotaru no haka (1988) - Starring: Isao Takahata (dir.), Tsutomu Tatsumi, Ayano Shiraishi 8.447697233834335
49 - Once Upon a Time in the West (1968) - Starring: Sergio Leone (dir.), Henry Fonda, Charles Bronson 8.447607652985626
50 - Rear Window (1954) - Starring: Alfred Hitchcock (dir.), James Stewart, Grace Kelly 8.437194134618084
51 - Alien (1979) - Starring: Ridley Scott (dir.), Sigourney Weaver, Tom Skerritt 8.435172983607936
52 - City Lights (1931) - Starring: Charles Chaplin (dir.), Charles Chaplin, Virginia Cherrill 8.434020628409375
53 - Nuovo Cinema Paradiso (1988) - Starring: Giuseppe Tornatore (dir.), Philippe Noiret, Enzo Cannavale 8.429202778530707
54 - Memento (2000) - Starring: Christopher Nolan (dir.), Guy Pearce, Carrie-Anne Moss 8.42582659660479
55 - Apocalypse Now (1979) - Starring: Francis Ford Coppola (dir.), Martin Sheen, Marlon Brando 8.425171809747907
56 - Raiders of the Lost Ark (1981) - Starring: Steven Spielberg (dir.), Harrison Ford, Karen Allen 8.411619426130699
57 - Django Unchained (2012) - Starring: Quentin Tarantino (dir.), Jamie Foxx, Christoph Waltz 8.402831625248117
58 - WALL·E (2008) - Starring: Andrew Stanton (dir.), Ben Burtt, Elissa Knight 8.392672664440767
59 - The Lives of Others (2006) - Starring: Florian Henckel von Donnersmarck (dir.), Ulrich Mühe, Martina Gedeck 8.386190498462541
60 - Sunset Blvd (1950) - Starring: Billy Wilder (dir.), William Holden, Gloria Swanson 8.3825006543051
61 - Paths of Glory (1957) - Starring: Stanley Kubrick (dir.), Kirk Douglas, Ralph Meeker 8.370854620746181
62 - The Shining (1980) - Starring: Stanley Kubrick (dir.), Jack Nicholson, Shelley Duvall 8.36782726691316
63 - The Great Dictator (1940) - Starring: Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard 8.36623085005408
64 - Witness for the Prosecution (1957) - Starring: Billy Wilder (dir.), Tyrone Power, Marlene Dietrich 8.356990391698849
65 - Avengers: Infinity War (2018) - Starring: Anthony Russo (dir.), Robert Downey Jr., Chris Hemsworth 8.355893850843332
66 - Aliens (1986) - Starring: James Cameron (dir.), Sigourney Weaver, Michael Biehn 8.344685661962945
67 - American Beauty (1999) - Starring: Sam Mendes (dir.), Kevin Spacey, Annette Bening 8.337719798464367
68 - Dr Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964) - Starring: Stanley Kubrick (dir.), Peter Sellers, George C. Scott 8.333508054532153
69 - Spider-Man: Into the Spider-Verse (2018) - Starring: Bob Persichetti (dir.), Shameik Moore, Jake Johnson 8.328896054136372
70 - The Dark Knight Rises (2012) - Starring: Christopher Nolan (dir.), Christian Bale, Tom Hardy 8.328631676859164
71 - Oldeuboi (2003) - Starring: Park Chan-wook (dir.), Choi Min-sik, Yoo Ji-Tae 8.319767121347349
72 - Joker (2019) - Starring: Todd Phillips (dir.), Joaquin Phoenix, Robert De Niro 8.319629159868846
73 - Amadeus (1984) - Starring: Milos Forman (dir.), F. Murray Abraham, Tom Hulce 8.315395281326584
74 - Braveheart (1995) - Starring: Mel Gibson (dir.), Mel Gibson, Sophie Marceau 8.315384639223199
75 - Toy Story (1995) - Starring: John Lasseter (dir.), Tom Hanks, Tim Allen 8.314759025150838
76 - Coco (2017) - Starring: Lee Unkrich (dir.), Anthony Gonzalez, Gael García Bernal 8.312155223465362
77 - Das Boot (1981) - Starring: Wolfgang Petersen (dir.), Jürgen Prochnow, Herbert Grönemeyer 8.311657834459602
78 - Inglourious Basterds (2009) - Starring: Quentin Tarantino (dir.), Brad Pitt, Diane Kruger 8.311027163741304
79 - Mononoke-hime (1997) - Starring: Hayao Miyazaki (dir.), Yôji Matsuda, Yuriko Ishida 8.303648290134106
80 - Avengers: Endgame (2019) - Starring: Anthony Russo (dir.), Robert Downey Jr., Chris Evans 8.301320697628332
81 - Once Upon a Time in America (1984) - Starring: Sergio Leone (dir.), Robert De Niro, James Woods 8.300365476872347
82 - Good Will Hunting (1997) - Starring: Gus Van Sant (dir.), Robin Williams, Matt Damon 8.286611950009068
83 - Requiem for a Dream (2000) - Starring: Darren Aronofsky (dir.), Ellen Burstyn, Jared Leto 8.276816167801151
84 - Toy Story 3 (2010) - Starring: Lee Unkrich (dir.), Tom Hanks, Tim Allen 8.27664969767002
85 - Kimi no na wa (2016) - Starring: Makoto Shinkai (dir.), Ryûnosuke Kamiki, Mone Kamishiraishi 8.274751220233636
86 - Singin' in the Rain (1952) - Starring: Stanley Donen (dir.), Gene Kelly, Donald O'Connor 8.273697403823817
87 - 3 Idiots (2009) - Starring: Rajkumar Hirani (dir.), Aamir Khan, Madhavan 8.269065017956754
88 - Star Wars: Episode VI - Return of the Jedi (1983) - Starring: Richard Marquand (dir.), Mark Hamill, Harrison Ford 8.267910918141057
89 - 2001: A Space Odyssey (1968) - Starring: Stanley Kubrick (dir.), Keir Dullea, Gary Lockwood 8.265208023692127
90 - Eternal Sunshine of the Spotless Mind (2004) - Starring: Michel Gondry (dir.), Jim Carrey, Kate Winslet 8.264461800886886
91 - Reservoir Dogs (1992) - Starring: Quentin Tarantino (dir.), Harvey Keitel, Tim Roth 8.264343669190005
92 - Tengoku to jigoku (1963) - Starring: Akira Kurosawa (dir.), Toshirô Mifune, Yutaka Sada 8.263414402332117
93 - Capharnaüm (2018) - Starring: Nadine Labaki (dir.), Zain Al Rafeea, Yordanos Shiferaw 8.258544985440885
94 - Citizen Kane (1941) - Starring: Orson Welles (dir.), Orson Welles, Joseph Cotten 8.25782964730644
95 - Lawrence of Arabia (1962) - Starring: David Lean (dir.), Peter O'Toole, Alec Guinness 8.256511787017153
96 - Jagten (2012) - Starring: Thomas Vinterberg (dir.), Mads Mikkelsen, Thomas Bo Larsen 8.255070041249953
97 - M - Eine Stadt sucht einen Mörder (1931) - Starring: Fritz Lang (dir.), Peter Lorre, Ellen Widmann 8.253703861278364
98 - North by Northwest (1959) - Starring: Alfred Hitchcock (dir.), Cary Grant, Eva Marie Saint 8.253652004540733
99 - Vertigo (1958) - Starring: Alfred Hitchcock (dir.), James Stewart, Kim Novak 8.248024468403582
10 -  Le fabuleux destin d'Amélie Poulain (2001) - Starring: Jean-Pierre Jeunet (dir.), Audrey Tautou, Mathieu Kassovitz 8.246001766154063
101 - A Clockwork Orange (1971) - Starring: Stanley Kubrick (dir.), Malcolm McDowell, Patrick Magee 8.244618734331517
102 - Idi i smotri (1985) - Starring: Elem Klimov (dir.), Aleksey Kravchenko, Olga Mironova 8.24359820762608
103 - Full Metal Jacket (1987) - Starring: Stanley Kubrick (dir.), Matthew Modine, R. Lee Ermey 8.239953705428745
104 - Double Indemnity (1944) - Starring: Billy Wilder (dir.), Fred MacMurray, Barbara Stanwyck 8.238143383609088
105 - The Apartment (1960) - Starring: Billy Wilder (dir.), Jack Lemmon, Shirley MacLaine 8.237302776265162
106 - Scarface (1983) - Starring: Brian De Palma (dir.), Al Pacino, Michelle Pfeiffer 8.235062968016791
107 - Ikiru (1952) - Starring: Akira Kurosawa (dir.), Takashi Shimura, Nobuo Kaneko 8.23121893750073
108 - The Sting (1973) - Starring: George Roy Hill (dir.), Paul Newman, Robert Redford 8.229065267323712
109 - To Kill a Mockingbird (1962) - Starring: Robert Mulligan (dir.), Gregory Peck, John Megna 8.228813685535203
110 - Taxi Driver (1976) - Starring: Martin Scorsese (dir.), Robert De Niro, Jodie Foster 8.227783196245355
111 - LA Confidential (1997) - Starring: Curtis Hanson (dir.), Kevin Spacey, Russell Crowe 8.224695326909774
112 - Up (2009) - Starring: Pete Docter (dir.), Edward Asner, Jordan Nagai 8.224318493255147
113 - Heat (1995) - Starring: Michael Mann (dir.), Al Pacino, Robert De Niro 8.223319610063779
114 - Hamilton (2020) - Starring: Thomas Kail (dir.), Lin-Manuel Miranda, Phillipa Soo 8.221867471245288
115 - Metropolis (1927) - Starring: Fritz Lang (dir.), Brigitte Helm, Alfred Abel 8.221041497985144
116 - Jodaeiye Nader az Simin (2011) - Starring: Asghar Farhadi (dir.), Payman Maadi, Leila Hatami 8.220510625821658
117 - Snatch (2000) - Starring: Guy Ritchie (dir.), Jason Statham, Brad Pitt 8.22036990774613
118 - Die Hard (1988) - Starring: John McTiernan (dir.), Bruce Willis, Alan Rickman 8.220216054943519
119 - Incendies (2010) - Starring: Denis Villeneuve (dir.), Lubna Azabal, Mélissa Désormeaux-Poulin 8.219404861773564
120 - Indiana Jones and the Last Crusade (1989) - Starring: Steven Spielberg (dir.), Harrison Ford, Sean Connery 8.21840001220467
121 - Ladri di biciclette (1948) - Starring: Vittorio De Sica (dir.), Lamberto Maggiorani, Enzo Staiola 8.217695773261683
122 - 1917 (2019) - Starring: Sam Mendes (dir.), Dean-Charles Chapman, George MacKay 8.212189930423829
123 - Spider-Man: No Way Home (2021) - Starring: Jon Watts (dir.), Tom Holland, Zendaya 8.210027116199669
124 - Taare Zameen Par (2007) - Starring: Aamir Khan (dir.), Darsheel Safary, Aamir Khan 8.2062770714976
125 - Der Untergang (2004) - Starring: Oliver Hirschbiegel (dir.), Bruno Ganz, Alexandra Maria Lara 8.204651111430056
126 - Per qualche dollaro in più (1965) - Starring: Sergio Leone (dir.), Clint Eastwood, Lee Van Cleef 8.203321526113973
127 - Batman Begins (2005) - Starring: Christopher Nolan (dir.), Christian Bale, Michael Caine 8.202120636754774
128 - Dangal (2016) - Starring: Nitesh Tiwari (dir.), Aamir Khan, Sakshi Tanwar 8.197393246085491
129 - The Kid (1921) - Starring: Charles Chaplin (dir.), Charles Chaplin, Edna Purviance 8.194496361950002
130 - Some Like It Hot (1959) - Starring: Billy Wilder (dir.), Marilyn Monroe, Tony Curtis 8.191555097230527
131 - The Father (2020) - Starring: Florian Zeller (dir.), Anthony Hopkins, Olivia Colman 8.182402812702849
132 - All About Eve (1950) - Starring: Joseph L. Mankiewicz (dir.), Bette Davis, Anne Baxter 8.180418088069262
133 - Green Book (2018) - Starring: Peter Farrelly (dir.), Viggo Mortensen, Mahershala Ali 8.174271297458331
134 - The Wolf of Wall Street (2013) - Starring: Martin Scorsese (dir.), Leonardo DiCaprio, Jonah Hill 8.17168741739976
135 - Judgment at Nuremberg (1961) - Starring: Stanley Kramer (dir.), Spencer Tracy, Burt Lancaster 8.168633356935784
136 - Everything Everywhere All at Once (2022) - Starring: Dan Kwan (dir.), Michelle Yeoh, Stephanie Hsu 8.16614238188375
137 - Unforgiven (1992) - Starring: Clint Eastwood (dir.), Clint Eastwood, Gene Hackman 8.16442784803575
138 - Ran (1985) - Starring: Akira Kurosawa (dir.), Tatsuya Nakadai, Akira Terao 8.163925642871371
139 - Casino (1995) - Starring: Martin Scorsese (dir.), Robert De Niro, Sharon Stone 8.163780246630663
140 - Pan's Labyrinth (2006) - Starring: Guillermo del Toro (dir.), Ivana Baquero, Ariadna Gil 8.163409184476642
141 - There Will Be Blood (2007) - Starring: Paul Thomas Anderson (dir.), Daniel Day-Lewis, Paul Dano 8.155068157711582
142 - The Sixth Sense (1999) - Starring: M. Night Shyamalan (dir.), Bruce Willis, Haley Joel Osment 8.153728676352138
143 - A Beautiful Mind (2001) - Starring: Ron Howard (dir.), Russell Crowe, Ed Harris 8.153104458526965
144 - Monty Python and the Holy Grail (1975) - Starring: Terry Gilliam (dir.), Graham Chapman, John Cleese 8.15231710303704
145 - The Truman Show (1998) - Starring: Peter Weir (dir.), Jim Carrey, Ed Harris 8.15190211577191

146 - Yôjinbô (1961) - Starring: Akira Kurosawa (dir.), Toshirô Mifune, Eijirô Tôno 8.149009584120193
147 - The Treasure of the Sierra Madre (1948) - Starring: John Huston (dir.), Humphrey Bogart, Walter Huston 8.14789110518559
148 - Shutter Island (2010) - Starring: Martin Scorsese (dir.), Leonardo DiCaprio, Emily Mortimer 8.143069706413307
149 - Rashômon (1950) - Starring: Akira Kurosawa (dir.), Toshirô Mifune, Machiko Kyô 8.143004124927856
150 - The Great Escape (1963) - Starring: John Sturges (dir.), Steve McQueen, James Garner 8.142212844708913
151 - Jurassic Park (1993) - Starring: Steven Spielberg (dir.), Sam Neill, Laura Dern 8.141571116400979
152 - Kill Bill: Vol 1 (2003) - Starring: Quentin Tarantino (dir.), Uma Thurman, David Carradine 8.137361690488929
153 - No Country for Old Men (2007) - Starring: Ethan Coen (dir.), Tommy Lee Jones, Javier Bardem 8.135608285455683
154 - Finding Nemo (2003) - Starring: Andrew Stanton (dir.), Albert Brooks, Ellen DeGeneres 8.131280062845056
155 - The Elephant Man (1980) - Starring: David Lynch (dir.), Anthony Hopkins, John Hurt 8.130830628034369
156 - Raging Bull (1980) - Starring: Martin Scorsese (dir.), Robert De Niro, Cathy Moriarty 8.129738447154738
157 - Chinatown (1974) - Starring: Roman Polanski (dir.), Jack Nicholson, Faye Dunaway 8.129569219048658
158 - Gone with the Wind (1939) - Starring: Victor Fleming (dir.), Clark Gable, Vivien Leigh 8.126774706244843
159 - V for Vendetta (2005) - Starring: James McTeigue (dir.), Hugo Weaving, Natalie Portman 8.125849956633312
160 - The Thing (1982) - Starring: John Carpenter (dir.), Kurt Russell, Wilford Brimley 8.125151274719274
161 - Inside Out (2015) - Starring: Pete Docter (dir.), Amy Poehler, Bill Hader 8.124428115445005
162 - Lock, Stock and Two Smoking Barrels (1998) - Starring: Guy Ritchie (dir.), Jason Flemyng, Dexter Fletcher 8.123310640268228
163 - Dial M for Murder (1954) - Starring: Alfred Hitchcock (dir.), Ray Milland, Grace Kelly 8.119192293656825
164 - El secreto de sus ojos (2009) - Starring: Juan José Campanella (dir.), Ricardo Darín, Soledad Villamil 8.117670045151149
165 - The Bridge on the River Kwai (1957) - Starring: David Lean (dir.), William Holden, Alec Guinness 8.114298864255606
166 - Hauru no ugoku shiro (2004) - Starring: Hayao Miyazaki (dir.), Chieko Baishô, Takuya Kimura 8.114257442042636
167 - Three Billboards Outside Ebbing, Missouri (2017) - Starring: Martin McDonagh (dir.), Frances McDormand, Woody Harrelson 8.111627561720521
168 - Trainspotting (1996) - Starring: Danny Boyle (dir.), Ewan McGregor, Ewen Bremner 8.111506993516793
169 - Gran Torino (2008) - Starring: Clint Eastwood (dir.), Clint Eastwood, Bee Vang 8.105034806589607
170 - Warrior (2011) - Starring: Gavin O'Connor (dir.), Tom Hardy, Nick Nolte 8.104977340869985
171 - Fargo (1996) - Starring: Joel Coen (dir.), William H. Macy, Frances McDormand 8.103492432043812
172 - Tonari no Totoro (1988) - Starring: Hayao Miyazaki (dir.), Hitoshi Takagi, Noriko Hidaka 8.095419031968756
173 - Prisoners (2013) - Starring: Denis Villeneuve (dir.), Hugh Jackman, Jake Gyllenhaal 8.095368416788322
174 - Million Dollar Baby (2004) - Starring: Clint Eastwood (dir.), Hilary Swank, Clint Eastwood 8.08994687412895
175 - The Gold Rush (1925) - Starring: Charles Chaplin (dir.), Charles Chaplin, Mack Swain 8.087746269474792
176 - Blade Runner (1982) - Starring: Ridley Scott (dir.), Harrison Ford, Rutger Hauer 8.086852660786384
177 - Catch Me If You Can (2002) - Starring: Steven Spielberg (dir.), Leonardo DiCaprio, Tom Hanks 8.086278601968043
178 - On the Waterfront (1954) - Starring: Elia Kazan (dir.), Marlon Brando, Karl Malden 8.084218265965557
179 - The Third Man (1949) - Starring: Carol Reed (dir.), Orson Welles, Joseph Cotten 8.082353810171082
180 - Bacheha-Ye aseman (1997) - Starring: Majid Majidi (dir.), Mohammad Amir Naji, Amir Farrokh Hashemian 8.08077942261366
181 - Ben-Hur (1959) - Starring: William Wyler (dir.), Charlton Heston, Jack Hawkins 8.07869394886637
182 - 12 Years a Slave (2013) - Starring: Steve McQueen (dir.), Chiwetel Ejiofor, Michael Kenneth Williams 8.07818930575461
183 - The General (1926) - Starring: Clyde Bruckman (dir.), Buster Keaton, Marion Mack 8.077710765142406
184 - Smultronstället (1957) - Starring: Ingmar Bergman (dir.), Victor Sjöström, Bibi Andersson 8.077455646090167
185 - Gone Girl (2014) - Starring: David Fincher (dir.), Ben Affleck, Rosamund Pike 8.077214309722036
186 - Before Sunrise (1995) - Starring: Richard Linklater (dir.), Ethan Hawke, Julie Delpy 8.076936804992373
187 - Harry Potter and the Deathly Hallows: Part 2 (2011) - Starring: David Yates (dir.), Daniel Radcliffe, Emma Watson 8.075973392264764
188 - The Deer Hunter (1978) - Starring: Michael Cimino (dir.), Robert De Niro, Christopher Walken 8.075606683332767
189 - In the Name of the Father (1993) - Starring: Jim Sheridan (dir.), Daniel Day-Lewis, Pete Postlethwaite 8.074260419838444
190 - The Grand Budapest Hotel (2014) - Starring: Wes Anderson (dir.), Ralph Fiennes, F. Murray Abraham 8.072523893616248
191 - Mr Smith Goes to Washington (1939) - Starring: Frank Capra (dir.), James Stewart, Jean Arthur 8.071131445657493
192 - Le salaire de la peur (1953) - Starring: Henri-Georges Clouzot (dir.), Yves Montand, Charles Vanel 8.069771524238519
193 - Barry Lyndon (1975) - Starring: Stanley Kubrick (dir.), Ryan O'Neal, Marisa Berenson 8.06949848326359
194 - Sherlock Jr (1924) - Starring: Buster Keaton (dir.), Buster Keaton, Kathryn McGuire 8.069059540981588
195 - Salinui chueok (2003) - Starring: Bong Joon Ho (dir.), Song Kang-ho, Kim Sang-kyung 8.068274551076566
196 - Room (2015) - Starring: Lenny Abrahamson (dir.), Brie Larson, Jacob Tremblay 8.06728328439246
197 - Klaus (2019) - Starring: Sergio Pablos (dir.), Jason Schwartzman, J.K. Simmons 8.067237460487794
198 - Hacksaw Ridge (2016) - Starring: Mel Gibson (dir.), Andrew Garfield, Sam Worthington 8.067119029362296
199 - Det sjunde inseglet (1957) - Starring: Ingmar Bergman (dir.), Max von Sydow, Gunnar Björnstrand 8.066365116378995
200 - Relatos salvajes (2014) - Starring: Damián Szifron (dir.), Darío Grandinetti, María Marull 8.065152328655799
201 - The Big Lebowski (1998) - Starring: Joel Coen (dir.), Jeff Bridges, John Goodman 8.062744343804713
202 - Mad Max: Fury Road (2015) - Starring: George Miller (dir.), Tom Hardy, Charlize Theron 8.061996593695818
203 - How to Train Your Dragon (2010) - Starring: Dean DeBlois (dir.), Jay Baruchel, Gerard Butler 8.061836456578202
204 - Mary and Max (2009) - Starring: Adam Elliot (dir.), Toni Collette, Philip Seymour Hoffman 8.060370221225702
205 - Monsters, Inc (2001) - Starring: Pete Docter (dir.), Billy Crystal, John Goodman 8.058661168549964
206 - Jaws (1975) - Starring: Steven Spielberg (dir.), Roy Scheider, Robert Shaw 8.057778435357616
207 - La passion de Jeanne d'Arc (1928) - Starring: Carl Theodor Dreyer (dir.), Maria Falconetti, Eugene Silvain 8.055095936617768
208 - Hotel Rwanda (2004) - Starring: Terry George (dir.), Don Cheadle, Sophie Okonedo 8.052804134304898
209 - Dead Poets Society (1989) - Starring: Peter Weir (dir.), Robin Williams, Robert Sean Leonard 8.052335726003912
210 - Tôkyô monogatari (1953) - Starring: Yasujirô Ozu (dir.), Chishû Ryû, Chieko Higashiyama 8.052000119509296
211 - Pather Panchali (1955) - Starring: Satyajit Ray (dir.), Kanu Bannerjee, Karuna Bannerjee 8.050512926098968
212 - Rocky (1976) - Starring: John G. Avildsen (dir.), Sylvester Stallone, Talia Shire 8.047251194925588
213 - Platoon (1986) - Starring: Oliver Stone (dir.), Charlie Sheen, Tom Berenger 8.047195030718663
214 - Ford v Ferrari (2019) - Starring: James Mangold (dir.), Matt Damon, Christian Bale 8.045906545791027
215 - Stand by Me (1986) - Starring: Rob Reiner (dir.), Wil Wheaton, River Phoenix 8.042116419218894
216 - The Terminator (1984) - Starring: James Cameron (dir.), Arnold Schwarzenegger, Linda Hamilton 8.041369224220613
217 - Spotlight (2015) - Starring: Tom McCarthy (dir.), Mark Ruffalo, Michael Keaton 8.039331432785385
218 - Rush (2013) - Starring: Ron Howard (dir.), Daniel Brühl, Chris Hemsworth 8.03912771645536
219 - Into the Wild (2007) - Starring: Sean Penn (dir.), Emile Hirsch, Vince Vaughn 8.037245629134851
220 - Network (1976) - Starring: Sidney Lumet (dir.), Faye Dunaway, William Holden 8.037139598964346
221 - The Wizard of Oz (1939) - Starring: Victor Fleming (dir.), Judy Garland, Frank Morgan 8.035702706330111
222 - Logan (2017) - Starring: James Mangold (dir.), Hugh Jackman, Patrick Stewart 8.035622237698762
223 - Groundhog Day (1993) - Starring: Harold Ramis (dir.), Bill Murray, Andie MacDowell 8.03237054048641
224 - Ratatouille (2007) - Starring: Brad Bird (dir.), Brad Garrett, Lou Romano 8.032357052853689
225 - Before Sunset (2004) - Starring: Richard Linklater (dir.), Ethan Hawke, Julie Delpy 8.028672722782447
226 - The Exorcist (1973) - Starring: William Friedkin (dir.), Ellen Burstyn, Max von Sydow 8.028244444582722
227 - The Best Years of Our Lives (1946) - Starring: William Wyler (dir.), Myrna Loy, Dana Andrews 8.026021378840783
228 - The Incredibles (2004) - Starring: Brad Bird (dir.), Craig T. Nelson, Samuel L. Jackson 8.02574549811398
229 - To Be or Not to Be (1942) - Starring: Ernst Lubitsch (dir.), Carole Lombard, Jack Benny 8.024785069181636
230 - Rebecca (1940) - Starring: Alfred Hitchcock (dir.), Laurence Olivier, Joan Fontaine 8.02267601732613
231 - The Grapes of Wrath (1940) - Starring: John Ford (dir.), Henry Fonda, Jane Darwell 8.022414502643766
232 - La battaglia di Algeri (1966) - Starring: Gillo Pontecorvo (dir.), Brahim Hadjadj, Jean Martin 8.022383112439842
233 - Hachi: A Dog's Tale (2009) - Starring: Lasse Hallström (dir.), Richard Gere, Joan Allen 8.021531545645193
234 - Cool Hand Luke (1967) - Starring: Stuart Rosenberg (dir.), Paul Newman, George Kennedy 8.021171642129321
235 - Amores perros (2000) - Starring: Alejandro G. Iñárritu (dir.), Emilio Echevarría, Gael García Bernal 8.020936279273679
236 - Pirates of the Caribbean: The Curse of the Black Pearl (2003) - Starring: Gore Verbinski (dir.), Johnny Depp, Geoffrey Rush 8.01900815084571
237 - La haine (1995) - Starring: Mathieu Kassovitz (dir.), Vincent Cassel, Hubert Koundé 8.016290473357698
238 - Les quatre cents coups (1959) - Starring: François Truffaut (dir.), Jean-Pierre Léaud, Albert Rémy 8.016050972666122
239 - Persona (1966) - Starring: Ingmar Bergman (dir.), Bibi Andersson, Liv Ullmann 8.015696668788786
240 - Babam ve Oglum (2005) - Starring: Cagan Irmak (dir.), Çetin Tekindor, Fikret Kuskan 8.014613059455726
241 - Life of Brian (1979) - Starring: Terry Jones (dir.), Graham Chapman, John Cleese 8.014550518419396
242 - Dersu Uzala (1975) - Starring: Akira Kurosawa (dir.), Maksim Munzuk, Yuriy Solomin 8.013759003886285
243 - It Happened One Night (1934) - Starring: Frank Capra (dir.), Clark Gable, Claudette Colbert 8.013741072124112
244 - The Sound of Music (1965) - Starring: Robert Wise (dir.), Julie Andrews, Christopher Plummer 8.013664943392504
245 - Ah-ga-ssi (2016) - Starring: Park Chan-wook (dir.), Kim Min-hee, Ha Jung-woo 8.009196169604849
246 - Jai Bhim (2021) - Starring: T.J. Gnanavel (dir.), Suriya, Lijo Mol Jose 8.007303573908162
247 - Aladdin (1992) - Starring: Ron Clements (dir.), Scott Weinger, Robin Williams 8.006973523210617
248 - Gandhi (1982) - Starring: Richard Attenborough (dir.), Ben Kingsley, John Gielgud 8.006342842734393
249 - The Help (2011) - Starring: Tate Taylor (dir.), Emma Stone, Viola Davis 8.00466721500111
250 - Beauty and the Beast (1991) - Starring: Gary Trousdale (dir.), Paige O'Hara, Robby Benson 8.003013012491198

In [63]:
df = pd.DataFrame(list)
df.head(100)

,place,movie_title,rating,year,star_cast
0,1,The Shawshank Redemption,9.233944969314647,1994,"Frank Darabont (dir.), Tim Robbins, Morgan Fre..."
1,2,The Godfather,9.156028704679505,1972,"Francis Ford Coppola (dir.), Marlon Brando, Al..."
2,3,The Dark Knight,8.985687692652556,2008,"Christopher Nolan (dir.), Christian Bale, Heat..."
3,4,The Godfather Part II,8.984186930445007,1974,"Francis Ford Coppola (dir.), Al Pacino, Robert..."
4,5,12 Angry Men,8.947801070232531,1957,"Sidney Lumet (dir.), Henry Fonda, Lee J. Cobb"
...,...,...,...,...,...
95,96,Jagten,8.255070041249953,2012,"Thomas Vinterberg (dir.), Mads Mikkelsen, Thom..."
96,97,M - Eine Stadt sucht einen Mörder,8.253703861278364,1931,"Fritz Lang (dir.), Peter Lorre, Ellen Widmann"
97,98,North by Northwest,8.253652004540733,1959,"Alfred Hitchcock (dir.), Cary Grant, Eva Marie..."
98,99,Vertigo,8.248024468403582,1958,"Alfred Hitchcock (dir.), James Stewart, Kim Novak"
99,10,Le fabuleux destin d'Amélie Poulain,8.246001766154063,2001,"Jean-Pierre Jeunet (dir.), Audrey Tautou, Math..."

In [33]:
#q4) #Write s python program to display list of respected former presidents of India(i.e. Name , Term of office) 
#from https://presidentofindia.nic.in/former-presidents.htm

import requests
from bs4 import BeautifulSoup
import pandas as pd

page = requests.get("https://presidentofindia.nic.in/former-presidents.htm")
soup = BeautifulSoup(page.content, 'html.parser')

items = []

datas = soup.select('div.presidentListing')
for elem in datas:
    name = elem.select('h3')[0].text
    terms = elem.select('p')[0].text
    info = {
        "President Name": name.strip(),
        "Term of Office": terms.strip().replace('Term of Office:', '')
    }
    items.append(info)
    
dataFrameData = pd.DataFrame.from_dict(items)

print(dataFrameData)

                                 President Name  \
0             Shri Pranab Mukherjee (1935-2020)
1   Smt Pratibha Devisingh Patil (birth - 1934)
2            DR. A.P.J. Abdul Kalam (1931-2015)
3            Shri K. R. Narayanan (1920 - 2005)
4           Dr Shankar Dayal Sharma (1918-1999)
5               Shri R Venkataraman (1910-2009)
6                  Giani Zail Singh (1916-1994)
7         Shri Neelam Sanjiva Reddy (1913-1996)
8          Dr. Fakhruddin Ali Ahmed (1905-1977)
9      Shri Varahagiri Venkata Giri (1894-1980)
10                 Dr. Zakir Husain (1897-1969)
11     Dr. Sarvepalli Radhakrishnan (1888-1975)
12              Dr. Rajendra Prasad (1884-1963)

                                       Term of Office
0                      25 July, 2012 to 25 July, 2017
1                      25 July, 2007 to 25 July, 2012
2                      25 July, 2002 to 25 July, 2007
3                      25 July, 1997 to 25 July, 2002
4                      25 July, 1992 to 25 July, 1997
5                      25 July, 1987 to 25 July, 1992
6                      25 July, 1982 to 25 July, 1987
7                      25 July, 1977 to 25 July, 1982
8                24 August, 1974 to 11 February, 1977
9    3 May, 1969 to 20 July, 1969 and 24 August, 1...
10                        13 May, 1967 to 3 May, 1969
11                       13 May, 1962 to 13 May, 1967
12                   26 January, 1950 to 13 May, 1962

In [126]:
#5) Write a python program to scrape cricket rankings from icc-cricket.com. You have to scrape:
#a) Top 10 ODI teams in men’s cricket along with the records for matches, points and rating.
# Downloading od data cricket
from urllib.request import urlopen
from bs4 import BeautifulSoup
html = urlopen('https://www.icc-cricket.com/rankings/mens/team-rankings/odi')
bs1 = BeautifulSoup(html, "html.parser")
titles = bs.find_all(['th', 'td'])
print('List all the header tags :', *titles, sep='\n\n')

List all the header tags :

<td class="rankings-block__position">1</td>

<td class="u-flex-center rankings-block__top-player-container">
<div class="rankings-block__player-image-container rankings-block__player-image-container--large">
<img alt="" class="rankings-block__player-image image-missing" data-error="true" data-player="7480" data-size="130x150" data-widget="player-image" src="//resources.pulse.icc-cricket.com/players/130x150/Photo-Missing.png"/>
</div>
<div class="rankings-block__banner--player-info rankings-block__banner--player-info-large u-text-left">
<div class="rankings-block__banner--name-large">Babar Azam</div>
<div class="rankings-block__banner--nationality">
<div class="flag-15 PAK"></div>
<span class="rankings-block__banner--nation"></span>PAK
<div class="rankings-block__banner--rating u-show-phablet">892</div>
</div>
</div>
</td>

<td class="u-hide-phablet u-align-bottom">
<div class="rankings-block__banner--rating">892</div>
</td>

<td class="u-text-right u-hide-phablet u-overflow-hidden">
<div class="rankings-block__career-best">
<span class="rankings-block__career-best-text">898 v West Indies, 10/06/2022</span>
<span class="circle-branding circle-branding--full-table circle-branding--top"></span>
<span class="circle-branding circle-branding--full-table circle-branding--bottom"></span>
</div>
</td>

<th class="table-head__cell u-text-right">Pos</th>

<th class="table-head__cell">Player</th>

<th class="table-head__cell">Team</th>

<th class="table-head__cell table-head__cell--rating u-text-right">Rating</th>

<td class="table-body__cell table-body__cell--position u-text-right">2</td>

<td class="table-body__cell rankings-table__name name">Imam-ul-Haq</td>

<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo PAK"></span>
<span class="table-body__logo-text">PAK</span>
</td>

<td class="table-body__cell rating u-text-right">815</td>

<td class="table-body__cell table-body__cell--position u-text-right">3</td>

<td class="table-body__cell rankings-table__name name">Virat Kohli</td>

<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo IND"></span>
<span class="table-body__logo-text">IND</span>
</td>

<td class="table-body__cell rating u-text-right">811</td>

<td class="table-body__cell table-body__cell--position u-text-right">4</td>

<td class="table-body__cell rankings-table__name name">Rohit Sharma</td>

<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo IND"></span>
<span class="table-body__logo-text">IND</span>
</td>

<td class="table-body__cell rating u-text-right">791</td>

<td class="table-body__cell table-body__cell--position u-text-right">5</td>

<td class="table-body__cell rankings-table__name name">Quinton de Kock</td>

<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo SA"></span>
<span class="table-body__logo-text">SA</span>
</td>

<td class="table-body__cell rating u-text-right">789</td>

<td class="table-body__cell table-body__cell--position u-text-right">6</td>

<td class="table-body__cell rankings-table__name name">Ross Taylor</td>

<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo NZ"></span>
<span class="table-body__logo-text">NZ</span>
</td>

<td class="table-body__cell rating u-text-right">775</td>

<td class="table-body__cell table-body__cell--position u-text-right">7</td>

<td class="table-body__cell rankings-table__name name">Rassie van der Dussen</td>

<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo SA"></span>
<span class="table-body__logo-text">SA</span>
</td>

<td class="table-body__cell rating u-text-right">769</td>

<td class="table-body__cell table-body__cell--position u-text-right">8</td>

<td class="table-body__cell rankings-table__name name">Jonny Bairstow</td>

<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo ENG"></span>
<span class="table-body__logo-text">ENG</span>
</td>

<td class="table-body__cell rating u-text-right">760</td>

<td class="table-body__cell table-body__cell--position u-text-right">9</td>

<td class="table-body__cell rankings-table__name name">David Warner</td>

<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo AUS"></span>
<span class="table-body__logo-text">AUS</span>
</td>

<td class="table-body__cell rating u-text-right">745</td>

<td class="table-body__cell table-body__cell--position u-text-right">10</td>

<td class="table-body__cell rankings-table__name name">Aaron Finch</td>

<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo AUS"></span>
<span class="table-body__logo-text">AUS</span>
</td>

<td class="table-body__cell rating u-text-right">727</td>

<td class="table-body__cell table-body__cell--position u-text-right">11</td>

<td class="table-body__cell rankings-table__name name">Joe Root</td>

<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo ENG"></span>
<span class="table-body__logo-text">ENG</span>
</td>

<td class="table-body__cell rating u-text-right">725</td>

<td class="table-body__cell table-body__cell--position u-text-right">12</td>

<td class="table-body__cell rankings-table__name name">Shai Hope</td>

<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo WI"></span>
<span class="table-body__logo-text">WI</span>
</td>

<td class="table-body__cell rating u-text-right">718</td>

<td class="table-body__cell table-body__cell--position u-text-right">13</td>

<td class="table-body__cell rankings-table__name name">Shikhar Dhawan</td>

<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo IND"></span>
<span class="table-body__logo-text">IND</span>
</td>

<td class="table-body__cell rating u-text-right">702</td>

<td class="table-body__cell table-body__cell--position u-text-right">14</td>

<td class="table-body__cell rankings-table__name name">Fakhar Zaman</td>

<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo PAK"></span>
<span class="table-body__logo-text">PAK</span>
</td>

<td class="table-body__cell rating u-text-right">701</td>

<td class="table-body__cell table-body__cell--position u-text-right">15</td>

<td class="table-body__cell rankings-table__name name">Martin Guptill</td>

<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo NZ"></span>
<span class="table-body__logo-text">NZ</span>
</td>

<td class="table-body__cell rating u-text-right">696</td>

<td class="table-body__cell table-body__cell--position u-text-right">16</td>

<td class="table-body__cell rankings-table__name name">Mushfiqur Rahim</td>

<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo BAN"></span>
<span class="table-body__logo-text">BAN</span>
</td>

<td class="table-body__cell rating u-text-right">691</td>

<td class="table-body__cell table-body__cell--position u-text-right">17</td>

<td class="table-body__cell rankings-table__name name">Jason Roy</td>

<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo ENG"></span>
<span class="table-body__logo-text">ENG</span>
</td>

<td class="table-body__cell rating u-text-right">679</td>

<td class="table-body__cell table-body__cell--position u-text-right">18</td>

<td class="table-body__cell rankings-table__name name">Glenn Maxwell</td>

<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo AUS"></span>
<span class="table-body__logo-text">AUS</span>
</td>

<td class="table-body__cell rating u-text-right">674</td>

<td class="table-body__cell table-body__cell--position u-text-right">19</td>

<td class="table-body__cell rankings-table__name name">Steve Smith</td>

<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo AUS"></span>
<span class="table-body__logo-text">AUS</span>
</td>

<td class="table-body__cell rating u-text-right">672</td>

<td class="table-body__cell table-body__cell--position u-text-right">20</td>

<td class="table-body__cell rankings-table__name name">Tamim Iqbal</td>

<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo BAN"></span>
<span class="table-body__logo-text">BAN</span>
</td>

<td class="table-body__cell rating u-text-right">662</td>

In [52]:
import pandas as pd
z=pd.read_html('https://www.icc-cricket.com/rankings/mens/team-rankings/odi')
z

[    Pos                Team  T  Matches  M  Points  P  Rating  R
 0     1        New Zealand  NZ          12       1505        125
 1     2           England  ENG          22       2756        125
 2     3          Pakistan  PAK          19       2005        106
 3     4             India  IND          22       2304        105
 4     5         Australia  AUS          23       2325        101
 5     6       South Africa  SA          19       1872         99
 6     7        Bangladesh  BAN          24       2275         95
 7     8          Sri Lanka  SL          29       2658         92
 8     9        West Indies  WI          32       2306         72
 9    10       Afghanistan  AFG          18       1238         69
 10   11           Ireland  IRE          20       1083         54
 11   12          Scotland  SCO          18        814         45
 12   13               UAE  UAE          19        724         38
 13   14       Netherlands  NED          18        603         34
 14   15          Zimbabwe  ZIM          17        539         32
 15   16              Oman  OMA          30        919         31
 16   17     United States  USA          20        544         27
 17   18           Namibia  NAM          11        246         22
 18   19             Nepal  NEP          18        298         17
 19   20  Papua New Guinea  PNG          22        134          6]

In [65]:
#5) Write a python program to scrape cricket rankings from icc-cricket.com. 
#bTop 10 ODI Batsmen along with the records of their team and rating.

from bs4 import BeautifulSoup
bs = BeautifulSoup(html, "html.parser")

In [1]:
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd
page2 = requests.get('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/all-time-batting')
xyz=pd.read_html('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/all-time-batting')
print(xyz[1].head())

   Pos           Player Team  Rating
0    2      Imam-ul-Haq  PAK     815
1    3      Virat Kohli  IND     811
2    4     Rohit Sharma  IND     791
3    5  Quinton de Kock   SA     789
4    6      Ross Taylor   NZ     775

In [118]:

columns = bs.find("thead").find_all("th")
column_names = [c.string for c in columns]

table_rows = bs.find("tbody").find_all("tr")
l = []
for tr in table_rows:
    td = tr.find_all('td')
    row = [str(tr.get_text()).strip() for tr in td]
    l.append(row)

df = pd.DataFrame(l, columns=column_names)
df.head(10)

  Pos                 Player Team Rating
0   2            Imam-ul-Haq  PAK    815
1   3            Virat Kohli  IND    811
2   4           Rohit Sharma  IND    791
3   5        Quinton de Kock   SA    789
4   6            Ross Taylor   NZ    775
5   7  Rassie van der Dussen   SA    769
6   8         Jonny Bairstow  ENG    760
7   9           David Warner  AUS    745
8  10            Aaron Finch  AUS    727
9  11               Joe Root  ENG    725

In [18]:
#5) Write a python program to scrape cricket rankings from icc-cricket.com. 
#c. Top 10 ODI bowlers along with the records of their team and rating.
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd
html = urlopen('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/all-time-bowling')
bs6 = BeautifulSoup(html, "html.parser")
titles = bs6.find_all(['th'])
print('List all the header tags :', *titles, sep='\n\n')

List all the header tags :

<th class="table-head__cell u-text-right">Pos</th>

<th class="table-head__cell">Player</th>

<th class="table-head__cell">Team</th>

<th class="table-head__cell table-head__cell--rating u-text-right">Rating</th>

In [19]:
page3 = requests.get('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/all-time-bowling')
page3

In [20]:
xy=pd.read_html('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/all-time-bowling')
print(xy[1].head())

   Pos            Player Team  Rating
0    2      Chris Woakes  ENG     686
1    3        Matt Henry   NZ     683
2    4    Shaheen Afridi  PAK     681
3    5    Jasprit Bumrah  IND     679
4    6  Mujeeb Ur Rahman  AFG     676

In [21]:

columns = bs6.find("thead").find_all("th")
column_names = [c.string for c in columns]
column_names

['Pos', 'Player', 'Team', 'Rating']

In [22]:

columns

[<th class="table-head__cell u-text-right">Pos</th>,
 <th class="table-head__cell">Player</th>,
 <th class="table-head__cell">Team</th>,
 <th class="table-head__cell table-head__cell--rating u-text-right">Rating</th>]

In [23]:
table_rows = bs6.find("tbody").find_all("tr")
c = []
for tr in table_rows:
    td = tr.find_all('td')
    row = [str(tr.get_text()).strip() for tr in td]
    c.append(row)

df1 = pd.DataFrame(c, columns = column_names)

In [24]:
df1.head(10)

  Pos            Player Team Rating
0   2      Chris Woakes  ENG    686
1   3        Matt Henry   NZ    683
2   4    Shaheen Afridi  PAK    681
3   5    Jasprit Bumrah  IND    679
4   6  Mujeeb Ur Rahman  AFG    676
5   7    Josh Hazlewood  AUS    667
6   8      Mehedi Hasan  BAN    661
7   9     Mohammad Nabi  AFG    657
8  10   Shakib Al Hasan  BAN    657
9  11       Rashid Khan  AFG    651

In [ ]:
#6) Write a python program to scrape cricket rankings from icc-cricket.com. You have to scrape:
#a) Top 10 ODI teams in women’s cricket along with the records for matches, points and rating.
#b) Top 10 women’s ODI Batting players along with the records of their team and rating.
#c) Top 10 women’s ODI all-rounder along with the records of their team and rating

In [1]:
#6) Write a #6) Write a python program to scrape cricket rankings from icc-cricket.com. You have to scrape:
#a) Top 10 ODI teams in women’s cricket along with the records for matches, points and rating.
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd
import pickle
import urllib.request,sys,time
from urllib.request import urlopen

In [2]:
page10 = requests.get('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/all-time-bowling')
page10

In [3]:
# Downloading od data cricket
from urllib.request import urlopen
from bs4 import BeautifulSoup
html = urlopen('https://www.icc-cricket.com/rankings/womens/team-rankings/odi')
bs20 = BeautifulSoup(html, "html.parser")

In [37]:
mn=pd.read_html('https://www.icc-cricket.com/rankings/womens/team-rankings/odi')
print(mn[0].head())

   Pos           Team  T  Matches  M  Points  P  Rating  R
0    1    Australia  AUS          29       4837        167
1    2  South Africa  SA          32       3949        123
2    3      England  ENG          30       3531        118
3    4        India  IND          29       2889        100
4    5   New Zealand  NZ          31       3019         97

In [4]:
columns = bs20.find("thead").find_all("th")
columns

[<th class="table-head__cell u-text-right">Pos</th>,
 <th class="table-head__cell rankings-table__team">
 <span class="u-hide-mobile">Team</span>
 <span class="u-show-mobile">T</span>
 </th>,
 <th class="table-head__cell u-center-text">
 <span class="u-hide-mobile">Matches</span>
 <span class="u-show-mobile">M</span>
 </th>,
 <th class="table-head__cell u-center-text">
 <span class="u-hide-mobile">Points</span>
 <span class="u-show-mobile">P</span>
 </th>,
 <th class="table-head__cell u-text-right rating">
 <span class="u-hide-mobile">Rating</span>
 <span class="u-show-mobile">R</span>
 </th>]

In [8]:
columns = bs20.find("table").find_all("th")
column_names = [c.string for c in columns]
column_names

['Pos', None, None, None, None]

In [6]:
table_rows = bs20.find("table").find_all("tr")
h = []
for tr in table_rows:
    td = tr.find_all('td')
    row = [str(tr.get_text()).strip() for tr in td]
    h.append(row)
df = pd.DataFrame(h, columns=column_names)

In [7]:
df.head(10)

    Pos              None  None   None  None
0  None              None  None   None  None
1     1    Australia\nAUS    29  4,837   167
2     2  South Africa\nSA    32  3,949   123
3     3      England\nENG    30  3,531   118
4     4        India\nIND    29  2,889   100
5     5   New Zealand\nNZ    31  3,019    97
6     6   West Indies\nWI    30  2,768    92
7     7   Bangladesh\nBAN    12    930    78
8     8     Pakistan\nPAK    30  1,962    65
9     9     Sri Lanka\nSL     8    384    48

In [ ]:
#6) Write a python program to scrape cricket rankings from icc-cricket.com. You have to scrape:
#b) Top 10 women’s ODI Batting players along with the records of their team and rating.

In [1]:
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd
import pickle
import urllib.request,sys,time
from urllib.request import urlopen

In [2]:
page11 = requests.get('https://www.icc-cricket.com/rankings/womens/player-rankings/odi/batting')
page11

In [3]:
# Downloading od data cricket
from urllib.request import urlopen
from bs4 import BeautifulSoup
html = urlopen('https://www.icc-cricket.com/rankings/womens/player-rankings/odi/batting')
bs21 = BeautifulSoup(html, "html.parser")

In [4]:
cd=pd.read_html('https://www.icc-cricket.com/rankings/womens/player-rankings/odi/batting')
print(cd[0].head())

                                                 Pos           Player Team  \
0                                             1  (0)     Alyssa Healy  AUS
1                                             2  (0)   Natalie Sciver  ENG
2                                             3  (0)      Beth Mooney  AUS
3  4  (1)  This player has moved up in the rankin...  Laura Wolvaardt   SA
4  5  (1)  This player has moved down in the rank...      Meg Lanning  AUS

   Rating             Career Best Rating
0     785      785 v England, 03/04/2022
1     750    750 v Australia, 03/04/2022
2     748      748 v England, 03/04/2022
3     713    741 v Australia, 22/03/2022
4     710  834 v New Zealand, 24/02/2016

In [5]:
columns = bs21.find("thead").find_all("th")
columns

[<th class="table-head__cell u-text-right">Pos</th>,
 <th class="table-head__cell">Player</th>,
 <th class="table-head__cell">Team</th>,
 <th class="table-head__cell table-head__cell--rating">Rating</th>,
 <th class="table-head__cell u-text-right u-hide-phablet">Career Best Rating</th>]

In [6]:
columns = bs21.find("thead").find_all("th")
column_names = [c.string for c in columns]
column_names

['Pos', 'Player', 'Team', 'Rating', 'Career Best Rating']

In [49]:
table_rows = bs21.find("table").find_all("tr")
a = []
for tr in table_rows:
    td = tr.find_all('td')
    row = [str(tr.get_text()).strip() for tr in td]
    a.append(row)

df = pd.DataFrame(a, columns = column_names)
df.head(10)

,Pos,Player,Team,Rating,Career Best Rating
0,None,None,None,None,None
1,1\n \n\n\n(0),Alyssa Healy,AUS,785,"785 v England, 03/04/2022"
2,2\n \n\n\n(0),Natalie Sciver,ENG,750,"750 v Australia, 03/04/2022"
3,3\n \n\n\n(0),Beth Mooney,AUS,748,"748 v England, 03/04/2022"
4,4\n \n\n\n\n\n(...,Laura Wolvaardt,SA,713,"741 v Australia, 22/03/2022"
5,5\n \n\n\n\n\n(...,Meg Lanning,AUS,710,"834 v New Zealand, 24/02/2016"
6,6\n \n\n\n(0),Rachael Haynes,AUS,701,"713 v West Indies, 15/03/2022"
7,7\n \n\n\n(0),Amy Satterthwaite,NZ,681,"756 v Australia, 02/03/2017"
8,8\n \n\n\n(0),Smriti Mandhana,IND,669,"797 v England, 28/02/2019"
9,9\n \n\n\n(0),Tammy Beaumont,ENG,659,"791 v India, 27/06/2021"

In [50]:
#6) Write a python program to scrape cricket rankings from icc-cricket.com. You have to scrape:

#c) Top 10 women’s ODI all-rounder along with the records of their team and rating

from bs4 import BeautifulSoup
import requests
import re
import pandas as pd
import pickle
import urllib.request,sys,time
from urllib.request import urlopen

In [51]:
page13 = requests.get('https://www.icc-cricket.com/rankings/womens/player-rankings/odi/all-rounder')
page13

In [52]:
# Downloading od data cricket
from urllib.request import urlopen
from bs4 import BeautifulSoup
html = urlopen('https://www.icc-cricket.com/rankings/womens/player-rankings/odi/all-rounder')
bs = BeautifulSoup(html, "html.parser")

In [53]:
ef=pd.read_html('https://www.icc-cricket.com/rankings/womens/player-rankings/odi/all-rounder')
print(ef[0].head())

                                                 Pos           Player Team  \
0                                             1  (0)   Natalie Sciver  ENG
1                                             2  (0)     Ellyse Perry  AUS
2  3  (1)  This player has moved up in the rankin...  Hayley Matthews   WI
3  4  (1)  This player has moved down in the rank...   Marizanne Kapp   SA
4                                             5  (0)      Amelia Kerr   NZ

   Rating              Career Best Rating
0     393     393 v Australia, 03/04/2022
1     374   548 v West Indies, 11/09/2019
2     338         365 v India, 12/03/2022
3     338   419 v West Indies, 10/09/2021
4     335  339 v South Africa, 17/03/2022

In [54]:
columns = bs.find("thead").find_all("th")
columns

[<th class="table-head__cell u-text-right">Pos</th>,
 <th class="table-head__cell">Player</th>,
 <th class="table-head__cell">Team</th>,
 <th class="table-head__cell table-head__cell--rating">Rating</th>,
 <th class="table-head__cell u-text-right u-hide-phablet">Career Best Rating</th>]

In [55]:
columns = bs.find("thead").find_all("th")
column_names = [c.string for c in columns]
column_names

['Pos', 'Player', 'Team', 'Rating', 'Career Best Rating']

In [56]:
table_rows = bs.find("table").find_all("tr")
f = []
for tr in table_rows:
    td = tr.find_all('td')
    row = [str(tr.get_text()).strip() for tr in td]
    f.append(row)

df = pd.DataFrame(f, columns = column_names)
df.head(10)

,Pos,Player,Team,Rating,Career Best Rating
0,None,None,None,None,None
1,1\n \n\n\n(0),Natalie Sciver,ENG,393,"393 v Australia, 03/04/2022"
2,2\n \n\n\n(0),Ellyse Perry,AUS,374,"548 v West Indies, 11/09/2019"
3,3\n \n\n\n\n\n(...,Hayley Matthews,WI,338,"365 v India, 12/03/2022"
4,4\n \n\n\n\n\n(...,Marizanne Kapp,SA,338,"419 v West Indies, 10/09/2021"
5,5\n \n\n\n(0),Amelia Kerr,NZ,335,"339 v South Africa, 17/03/2022"
6,6\n \n\n\n(0),Ashleigh Gardner,AUS,269,"279 v West Indies, 30/03/2022"
7,7\n \n\n\n(0),Deepti Sharma,IND,249,"397 v South Africa, 09/10/2019"
8,8\n \n\n\n(0),Jess Jonassen,AUS,245,"308 v West Indies, 11/09/2019"
9,9\n \n\n\n\n\n(...,Sune Luus,SA,223,"223 v Ireland, 17/06/2022"

In [ ]:
 # q7  Write a python program to scrape mentioned news details from https://www.cnbc.com/world/?region=world :
#i) Headline
#ii) Time
#iii) News Link

In [7]:
from newspaper import Article
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd
import pickle
import urllib.request,sys,time
from urllib.request import urlopen

In [9]:
page5 = requests.get('https://www.cnbc.com/world/?region=world')
page5

In [10]:
html = urlopen('https://www.cnbc.com/world/?region=world')
bs8 = BeautifulSoup(html, "html.parser")

In [11]:
pagesToGet= 1

upperframe=[]  
for page in range(1,pagesToGet+1):
    print('processing page :', page)
    url = 'https://www.cnbc.com/world/?region=world'+str(page)
    print(url)

processing page : 1
https://www.cnbc.com/world/?region=world1

In [24]:
Headline = []
for i in bs8.find_all("a",class_="LatestNews-headline"): 
    Headline.append(i.text)
Headline

['The architect helping tech giants redesign offices for hybrid work',
 'Fierce local battles over power lines are a bottleneck for clean energy',
 'These are the 5 best—and worst—states for women-owned businesses in America',
 'Here’s what’s next for crypto exchanges as no-fee trading may affect revenue',
 "Some 'Secure 2.0' proposals in the Senate look different from the House version",
 'Goldman analysts love these stocks, but the rest of Wall Street not so much',
 'Exxon Mobil CEO cautions an abrupt energy transition could raise gas prices',
 'G-7 nations to announce import ban on Russian gold as Moscow sanctions widen',
 'World Health Organization says monkeypox is not a global health emergency right now',
 'RI cop arrested for assault on political opponent at abortion rights rally',
 "This couple left the U.S. to live abroad and save money: 'We've been to London, Rome and Lisbon'",
 'President Biden signs bipartisan gun reform bill into law',
 "El Salvador's $425 million bitcoin experiment isn't saving the country's finances",
 "Social Security isn't bankrupt: What we know about future benefits",
 'Recruiters say tech job market is still hot, despite isolated layoffs',
 "Back-to-school preview: Recession looms over retailers' busiest half of the year",
 'Goldman Sachs names several top stocks to weather the market storm',
 'Every new car sold in the world will be electric by 2040, says Exxon Mobil CEO',
 'Stay away from this company poised to go public next week, Jim Cramer warns',
 "Cramer's lightning round: Move on from DigitalBridge",
 'Google memo on end of Roe v. Wade says employees may apply to relocate',
 'Tech leaders react to Roe v. Wade reversal',
 "'I'm outraged:' Women react to Roe v. Wade ruling outside of Supreme Court",
 'Cramer’s week ahead: Next week will be a bellwether for upcoming earnings season',
 'Frontier Airlines sweetens offer for Spirit merger as shareholder vote looms',
 'Best trades on CNBC Friday: Pros put money in these tech and consumer stocks',
 "Roe v. Wade's demise forces companies to grapple with health plans, privacy",
 'Airlines, FAA spar over flight delays ahead of crucial July Fourth weekend',
 'Investing Club: The week in review, the week ahead — June 24, 2022',
 'Disney, Apple and Amazon keep waiting as NFL considers Sunday Ticket offers']

In [29]:
Time = []
for i in bs8.find_all("time",class_="LatestNews-timestamp"): 
    Time.append(i.text)
Time

['2 Hours Ago',
 '2 Hours Ago',
 '2 Hours Ago',
 '2 Hours Ago',
 '3 Hours Ago',
 '3 Hours Ago',
 '3 Hours Ago',
 '7 Hours Ago',
 '17 Hours Ago',
 '20 Hours Ago',
 '24 Hours Ago',
 'June 25, 2022',
 'June 25, 2022',
 'June 25, 2022',
 'June 25, 2022',
 'June 25, 2022',
 'June 25, 2022',
 'June 25, 2022',
 'June 24, 2022',
 'June 24, 2022',
 'June 24, 2022',
 'June 24, 2022',
 'June 24, 2022',
 'June 24, 2022',
 'June 24, 2022',
 'June 24, 2022',
 'June 24, 2022',
 'June 24, 2022',
 'June 24, 2022',
 'June 24, 2022']

In [26]:
News_Link = []
News_Link  = bs8.find_all("a", attrs={"class": "LatestNews-headline"})
News_Link

[<a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/26/meet-the-architect-helping-tech-firms-like-intuit-redesign-the-office.html" title="The architect helping tech giants redesign offices for hybrid work">The architect helping tech giants redesign offices for hybrid work</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/26/why-the-us-has-a-massive-power-line-problem.html" title="Fierce local battles over power lines are a bottleneck for clean energy">Fierce local battles over power lines are a bottleneck for clean energy</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/26/the-5-best-and-worst-states-for-women-owned-businesses-in-america.html" title="These are the 5 best—and worst—states for women-owned businesses in America">These are the 5 best—and worst—states for women-owned businesses in America</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/26/no-fee-trading-has-arrived-for-crypto-heres-what-that-may-mean-for-revenue-at-these-companies.html" title="Here’s what’s next for crypto exchanges as no-fee trading may affect revenue">Here’s what’s next for crypto exchanges as no-fee trading may affect revenue</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/26/not-all-secure-2point0-proposals-in-the-house-and-senate-are-the-same.html" title="Some 'Secure 2.0' proposals in the Senate look different from the House version">Some 'Secure 2.0' proposals in the Senate look different from the House version</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/26/goldman-analysts-love-these-stocks-not-so-the-rest-of-wall-street.html" title="Goldman analysts love these stocks, but the rest of Wall Street not so much">Goldman analysts love these stocks, but the rest of Wall Street not so much</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/26/exxon-mobil-ceo-darren-woods-on-energy-transition-gas-prices.html" title="Exxon Mobil CEO cautions an abrupt energy transition could raise gas prices">Exxon Mobil CEO cautions an abrupt energy transition could raise gas prices</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/26/g-7-nations-to-announce-import-ban-on-russian-gold.html" title="G-7 nations to announce import ban on Russian gold as Moscow sanctions widen">G-7 nations to announce import ban on Russian gold as Moscow sanctions widen</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/25/world-health-organization-says-monkeypox-is-not-a-global-health-emergency-right-now.html" title="World Health Organization says monkeypox is not a global health emergency right now">World Health Organization says monkeypox is not a global health emergency right now</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/25/ri-cop-allegedly-attacks-political-opponent-at-abortion-rally-after-roe-ruling.html" title="RI cop arrested for assault on political opponent at abortion rights rally">RI cop arrested for assault on political opponent at abortion rights rally</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/25/this-couple-left-the-us-to-travel-work-full-time-heres-how-much-money-they-save-a-month-now.html" title="This couple left the U.S. to live abroad and save money: 'We've been to London, Rome and Lisbon'">This couple left the U.S. to live abroad and save money: 'We've been to London, Rome and Lisbon'</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/25/president-biden-signs-bipartisan-gun-reform-bill-into-law.html" title="President Biden signs bipartisan gun reform bill into law">President Biden signs bipartisan gun reform bill into law</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/25/el-salvador-bitcoin-experiment-not-saving-countrys-finances.html" title="El Salvador's $425 million bitcoin experiment isn't saving the country's finances">El Salvador's $425 million bitcoin experiment isn't saving the country's finances</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/25/social-security-isnt-bankrupt-what-we-know-about-future-benefits.html" title="Social Security isn't bankrupt: What we know about future benefits">Social Security isn't bankrupt: What we know about future benefits</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/25/tech-job-market-still-very-hot-despite-isolated-layoffs.html" title="Recruiters say tech job market is still hot, despite isolated layoffs">Recruiters say tech job market is still hot, despite isolated layoffs</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/25/consumers-grow-stressed-as-retailers-gear-up-for-back-to-school-shopping.html" title="Back-to-school preview: Recession looms over retailers' busiest half of the year">Back-to-school preview: Recession looms over retailers' busiest half of the year</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/25/buy-stocks-like-lululemon-brinks-as-recession-fears-mount.html" title="Goldman Sachs names several top stocks to weather the market storm">Goldman Sachs names several top stocks to weather the market storm</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/25/exxon-mobil-ceo-all-new-passenger-cars-will-be-electric-by-2040.html" title="Every new car sold in the world will be electric by 2040, says Exxon Mobil CEO">Every new car sold in the world will be electric by 2040, says Exxon Mobil CEO</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/24/stay-away-from-this-company-poised-to-go-public-next-week-jim-cramer-warns.html" title="Stay away from this company poised to go public next week, Jim Cramer warns">Stay away from this company poised to go public next week, Jim Cramer warns</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/24/cramers-lightning-round-move-on-from-digitalbridge.html" title="Cramer's lightning round: Move on from DigitalBridge">Cramer's lightning round: Move on from DigitalBridge</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/24/google-memo-to-employees-on-roe-v-wade-overturn.html" title="Google memo on end of Roe v. Wade says employees may apply to relocate">Google memo on end of Roe v. Wade says employees may apply to relocate</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/24/tech-execs-react-to-roe-v-wade-reversal-gates-sandberg-wojcicki.html" title="Tech leaders react to Roe v. Wade reversal">Tech leaders react to Roe v. Wade reversal</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/24/im-outraged-women-react-to-roe-v-wade-ruling-outside-of-supreme-court.html" title="'I'm outraged:' Women react to Roe v. Wade ruling outside of Supreme Court">'I'm outraged:' Women react to Roe v. Wade ruling outside of Supreme Court</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/24/cramers-week-ahead-next-week-will-be-a-bellwether-for-the-upcoming-earnings-season.html" title="Cramer’s week ahead: Next week will be a bellwether for upcoming earnings season">Cramer’s week ahead: Next week will be a bellwether for upcoming earnings season</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/24/frontier-sweetens-offer-for-spirit-airlines-merger-as-shareholder-vote-looms.html" title="Frontier Airlines sweetens offer for Spirit merger as shareholder vote looms">Frontier Airlines sweetens offer for Spirit merger as shareholder vote looms</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/24/best-trades-on-cnbc-friday-pros-put-money-in-tech-and-consumer-stocks.html" title="Best trades on CNBC Friday: Pros put money in these tech and consumer stocks">Best trades on CNBC Friday: Pros put money in these tech and consumer stocks</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/24/roe-v-wade-abortion-decision-companies-forced-to-weigh-in-on-privacy-health-care.html" title="Roe v. Wade's demise forces companies to grapple with health plans, privacy">Roe v. Wade's demise forces companies to grapple with health plans, privacy</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/24/airlines-faa-spar-over-flight-delays-ahead-of-july-fourth.html" title="Airlines, FAA spar over flight delays ahead of crucial July Fourth weekend">Airlines, FAA spar over flight delays ahead of crucial July Fourth weekend</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/24/investing-club-the-week-in-review-the-week-ahead-june-24-2022.html" title="Investing Club: The week in review, the week ahead — June 24, 2022">Investing Club: The week in review, the week ahead — June 24, 2022</a>,
 <a class="LatestNews-headline" href="https://www.cnbc.com/2022/06/24/disney-apple-and-amazon-keep-waiting-as-nfl-considers-sunday-ticket-offers.html" title="Disney, Apple and Amazon keep waiting as NFL considers Sunday Ticket offers">Disney, Apple and Amazon keep waiting as NFL considers Sunday Ticket offers</a>]

In [30]:
print(len(Headline), len(Time), len(News_Link))

30 30 30

In [32]:
import pandas as pd
df = pd.DataFrame({'Headline': Headline, 'Time': Time, 'News_Link': News_Link})
df

,Headline,Time,News_Link
0,The architect helping tech giants redesign off...,2 Hours Ago,[The architect helping tech giants redesign of...
1,Fierce local battles over power lines are a bo...,2 Hours Ago,[Fierce local battles over power lines are a b...
2,These are the 5 best—and worst—states for wome...,2 Hours Ago,[These are the 5 best—and worst—states for wom...
3,Here’s what’s next for crypto exchanges as no-...,2 Hours Ago,[Here’s what’s next for crypto exchanges as no...
4,Some 'Secure 2.0' proposals in the Senate look...,3 Hours Ago,[Some 'Secure 2.0' proposals in the Senate loo...
5,"Goldman analysts love these stocks, but the re...",3 Hours Ago,"[Goldman analysts love these stocks, but the r..."
6,Exxon Mobil CEO cautions an abrupt energy tran...,3 Hours Ago,[Exxon Mobil CEO cautions an abrupt energy tra...
7,G-7 nations to announce import ban on Russian ...,7 Hours Ago,[G-7 nations to announce import ban on Russian...
8,World Health Organization says monkeypox is no...,17 Hours Ago,[World Health Organization says monkeypox is n...
9,RI cop arrested for assault on political oppon...,20 Hours Ago,[RI cop arrested for assault on political oppo...
10,This couple left the U.S. to live abroad and s...,24 Hours Ago,[This couple left the U.S. to live abroad and ...
11,President Biden signs bipartisan gun reform bi...,"June 25, 2022",[President Biden signs bipartisan gun reform b...
12,El Salvador's $425 million bitcoin experiment ...,"June 25, 2022",[El Salvador's $425 million bitcoin experiment...
13,Social Security isn't bankrupt: What we know a...,"June 25, 2022",[Social Security isn't bankrupt: What we know ...
14,"Recruiters say tech job market is still hot, d...","June 25, 2022","[Recruiters say tech job market is still hot, ..."
15,Back-to-school preview: Recession looms over r...,"June 25, 2022",[Back-to-school preview: Recession looms over ...
16,Goldman Sachs names several top stocks to weat...,"June 25, 2022",[Goldman Sachs names several top stocks to wea...
17,Every new car sold in the world will be electr...,"June 25, 2022",[Every new car sold in the world will be elect...
18,Stay away from this company poised to go publi...,"June 24, 2022",[Stay away from this company poised to go publ...
19,Cramer's lightning round: Move on from Digital...,"June 24, 2022",[Cramer's lightning round: Move on from Digita...
20,Google memo on end of Roe v. Wade says employe...,"June 24, 2022",[Google memo on end of Roe v. Wade says employ...
21,Tech leaders react to Roe v. Wade reversal,"June 24, 2022",[Tech leaders react to Roe v. Wade reversal]
22,'I'm outraged:' Women react to Roe v. Wade rul...,"June 24, 2022",['I'm outraged:' Women react to Roe v. Wade ru...
23,Cramer’s week ahead: Next week will be a bellw...,"June 24, 2022",[Cramer’s week ahead: Next week will be a bell...
24,Frontier Airlines sweetens offer for Spirit me...,"June 24, 2022",[Frontier Airlines sweetens offer for Spirit m...
25,Best trades on CNBC Friday: Pros put money in ...,"June 24, 2022",[Best trades on CNBC Friday: Pros put money in...
26,Roe v. Wade's demise forces companies to grapp...,"June 24, 2022",[Roe v. Wade's demise forces companies to grap...
27,"Airlines, FAA spar over flight delays ahead of...","June 24, 2022","[Airlines, FAA spar over flight delays ahead o..."
28,"Investing Club: The week in review, the week a...","June 24, 2022","[Investing Club: The week in review, the week ..."
29,"Disney, Apple and Amazon keep waiting as NFL c...","June 24, 2022","[Disney, Apple and Amazon keep waiting as NFL ..."

In [ ]:
#q8. Write a python program to scrape the details of most downloaded articles from AI in last 90 days. 
#https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles
#Scrape below mentioned details :
#i) Paper Title 
#ii) Authors
#iii) Published Date 
#iv) Paper URL

In [1]:
from newspaper import Article
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd
import pickle
import urllib.request,sys,time
from urllib.request import urlopen

In [2]:
page4 = requests.get('https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles')
page4

In [3]:
html = urlopen('https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles')
bs7 = BeautifulSoup(html, "html.parser")

In [5]:
pagesToGet= 1

upperframe=[]  
for page in range(1,pagesToGet+1):
    print('processing page :', page)
    url = 'https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles'+str(page)
    print(url)

processing page : 1
https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles1

In [16]:
Paper_url = []
Paper_url  = bs7.find_all("a", attrs={"class": "sc-5smygv-0 nrDZj"})
Paper_url

[<a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370221000862"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">Reward is enough</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370221000722"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">Making sense of raw input</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370215000910"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">Law and logic: A review from an argumentation perspective</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370298000551"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">Creativity and artificial intelligence</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370216300790"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">Artificial cognition for social human–robot interaction: An implementation</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370218305988"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">Explanation in artificial intelligence: Insights from the social sciences</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370220301855"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">Making sense of sensory input</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370214001386"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">Conflict-based search for optimal multi-agent pathfinding</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370299000521"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">Between MDPs and semi-MDPs: A framework for temporal abstraction in reinforcement learning</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370219300116"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">The Hanabi challenge: A new frontier for AI research</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370220301533"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">Evaluating XAI: A comparison of rule-based and example-based explanations</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370207000793"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">Argumentation in artificial intelligence</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370216300285"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">Algorithms for computing strategies in two-player simultaneous move games</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370220301958"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">Multiple object tracking: A literature review</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370297000635"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">Selection of relevant features and examples in machine learning</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370221000515"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">A survey of inverse reinforcement learning: Challenges, methods and progress</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370221000539"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">Explaining individual predictions when features are dependent: More accurate approximations to Shapley values</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370221000096"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">A review of possible effects of cognitive biases on interpretation of rule-based machine learning models</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370216300868"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">Integrating social power into the decision-making of cognitive agents</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370221000588"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">“That's (not) the output I expected!” On the role of end user expectations in creating explanations of AI systems</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370221000102"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">Explaining black-box classifiers using post-hoc explanations-by-example: The effect of explanations and error-rates in XAI user studies</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370213001082"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">Algorithm runtime prediction: Methods &amp; evaluation</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S000437029700043X"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">Wrappers for feature subset selection</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370221000734"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">Commonsense visual sensemaking for autonomous driving – On generalised neurosymbolic online abduction integrating vision and semantics</h2></a>,
 <a class="sc-5smygv-0 nrDZj" href="https://www.sciencedirect.com/science/article/pii/S0004370209001398"><h2 class="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR">Quantum computation, quantum theory and AI</h2></a>]

In [12]:
Paper_Title = []
for i in bs7.find_all("h2",class_="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR"): 
    Paper_Title.append(i.text)
Paper_Title

['Reward is enough',
 'Making sense of raw input',
 'Law and logic: A review from an argumentation perspective',
 'Creativity and artificial intelligence',
 'Artificial cognition for social human–robot interaction: An implementation',
 'Explanation in artificial intelligence: Insights from the social sciences',
 'Making sense of sensory input',
 'Conflict-based search for optimal multi-agent pathfinding',
 'Between MDPs and semi-MDPs: A framework for temporal abstraction in reinforcement learning',
 'The Hanabi challenge: A new frontier for AI research',
 'Evaluating XAI: A comparison of rule-based and example-based explanations',
 'Argumentation in artificial intelligence',
 'Algorithms for computing strategies in two-player simultaneous move games',
 'Multiple object tracking: A literature review',
 'Selection of relevant features and examples in machine learning',
 'A survey of inverse reinforcement learning: Challenges, methods and progress',
 'Explaining individual predictions when features are dependent: More accurate approximations to Shapley values',
 'A review of possible effects of cognitive biases on interpretation of rule-based machine learning models',
 'Integrating social power into the decision-making of cognitive agents',
 "“That's (not) the output I expected!” On the role of end user expectations in creating explanations of AI systems",
 'Explaining black-box classifiers using post-hoc explanations-by-example: The effect of explanations and error-rates in XAI user studies',
 'Algorithm runtime prediction: Methods & evaluation',
 'Wrappers for feature subset selection',
 'Commonsense visual sensemaking for autonomous driving – On generalised neurosymbolic online abduction integrating vision and semantics',
 'Quantum computation, quantum theory and AI']

In [13]:
Authors = []
for i in bs7.find_all("span",class_="sc-1w3fpd7-0 pgLAT"): 
    Authors.append(i.text)
Authors

['Silver, David, Singh, Satinder, Precup, Doina, Sutton, Richard S. ',
 'Evans, Richard, Bošnjak, Matko and 5 more',
 'Prakken, Henry, Sartor, Giovanni ',
 'Boden, Margaret A. ',
 'Lemaignan, Séverin, Warnier, Mathieu and 3 more',
 'Miller, Tim ',
 'Evans, Richard, Hernández-Orallo, José and 3 more',
 'Sharon, Guni, Stern, Roni, Felner, Ariel, Sturtevant, Nathan R. ',
 'Sutton, Richard S., Precup, Doina, Singh, Satinder ',
 'Bard, Nolan, Foerster, Jakob N. and 13 more',
 'van der Waa, Jasper, Nieuwburg, Elisabeth, Cremers, Anita, Neerincx, Mark ',
 'Bench-Capon, T.J.M., Dunne, Paul E. ',
 'Bošanský, Branislav, Lisý, Viliam and 3 more',
 'Luo, Wenhan, Xing, Junliang and 4 more',
 'Blum, Avrim L., Langley, Pat ',
 'Arora, Saurabh, Doshi, Prashant ',
 'Aas, Kjersti, Jullum, Martin, Løland, Anders ',
 'Kliegr, Tomáš, Bahník, Štěpán, Fürnkranz, Johannes ',
 'Pereira, Gonçalo, Prada, Rui, Santos, Pedro A. ',
 'Riveiro, Maria, Thill, Serge ',
 'Kenny, Eoin M., Ford, Courtney, Quinn, Molly, Keane, Mark T. ',
 'Hutter, Frank, Xu, Lin, Hoos, Holger H., Leyton-Brown, Kevin ',
 'Kohavi, Ron, John, George H. ',
 'Suchan, Jakob, Bhatt, Mehul, Varadarajan, Srikrishna ',
 'Ying, Mingsheng ']

In [14]:
Pubished_Date = []
for i in bs7.find_all("span",class_="sc-1thf9ly-2 bKddwo"): 
    Pubished_Date.append(i.text)
Pubished_Date

['October 2021',
 'October 2021',
 'October 2015',
 'August 1998',
 'June 2017',
 'February 2019',
 'April 2021',
 'February 2015',
 'August 1999',
 'March 2020',
 'February 2021',
 'October 2007',
 'August 2016',
 'April 2021',
 'December 1997',
 'August 2021',
 'September 2021',
 'June 2021',
 'December 2016',
 'September 2021',
 'May 2021',
 'January 2014',
 'December 1997',
 'October 2021',
 'February 2010']

In [17]:
print(len(Paper_Title), len(Authors), len(Pubished_Date), len(Paper_url))

25 25 25 25

In [18]:
import pandas as pd
df = pd.DataFrame({'Paper_Title': Paper_Title, 'Authors': Authors, 'Pubished_Date': Pubished_Date, 'Paper_url': Paper_url})
df

,Paper_Title,Authors,Pubished_Date,Paper_url
0,Reward is enough,"Silver, David, Singh, Satinder, Precup, Doina,...",October 2021,[[Reward is enough]]
1,Making sense of raw input,"Evans, Richard, Bošnjak, Matko and 5 more",October 2021,[[Making sense of raw input]]
2,Law and logic: A review from an argumentation ...,"Prakken, Henry, Sartor, Giovanni",October 2015,[[Law and logic: A review from an argumentatio...
3,Creativity and artificial intelligence,"Boden, Margaret A.",August 1998,[[Creativity and artificial intelligence]]
4,Artificial cognition for social human–robot in...,"Lemaignan, Séverin, Warnier, Mathieu and 3 more",June 2017,[[Artificial cognition for social human–robot ...
5,Explanation in artificial intelligence: Insigh...,"Miller, Tim",February 2019,[[Explanation in artificial intelligence: Insi...
6,Making sense of sensory input,"Evans, Richard, Hernández-Orallo, José and 3 more",April 2021,[[Making sense of sensory input]]
7,Conflict-based search for optimal multi-agent ...,"Sharon, Guni, Stern, Roni, Felner, Ariel, Stur...",February 2015,[[Conflict-based search for optimal multi-agen...
8,Between MDPs and semi-MDPs: A framework for te...,"Sutton, Richard S., Precup, Doina, Singh, Sati...",August 1999,[[Between MDPs and semi-MDPs: A framework for ...
9,The Hanabi challenge: A new frontier for AI re...,"Bard, Nolan, Foerster, Jakob N. and 13 more",March 2020,[[The Hanabi challenge: A new frontier for AI ...
10,Evaluating XAI: A comparison of rule-based and...,"van der Waa, Jasper, Nieuwburg, Elisabeth, Cre...",February 2021,[[Evaluating XAI: A comparison of rule-based a...
11,Argumentation in artificial intelligence,"Bench-Capon, T.J.M., Dunne, Paul E.",October 2007,[[Argumentation in artificial intelligence]]
12,Algorithms for computing strategies in two-pla...,"Bošanský, Branislav, Lisý, Viliam and 3 more",August 2016,[[Algorithms for computing strategies in two-p...
13,Multiple object tracking: A literature review,"Luo, Wenhan, Xing, Junliang and 4 more",April 2021,[[Multiple object tracking: A literature review]]
14,Selection of relevant features and examples in...,"Blum, Avrim L., Langley, Pat",December 1997,[[Selection of relevant features and examples ...
15,A survey of inverse reinforcement learning: Ch...,"Arora, Saurabh, Doshi, Prashant",August 2021,[[A survey of inverse reinforcement learning: ...
16,Explaining individual predictions when feature...,"Aas, Kjersti, Jullum, Martin, Løland, Anders",September 2021,[[Explaining individual predictions when featu...
17,A review of possible effects of cognitive bias...,"Kliegr, Tomáš, Bahník, Štěpán, Fürnkranz, Joha...",June 2021,[[A review of possible effects of cognitive bi...
18,Integrating social power into the decision-mak...,"Pereira, Gonçalo, Prada, Rui, Santos, Pedro A.",December 2016,[[Integrating social power into the decision-m...
19,“That's (not) the output I expected!” On the r...,"Riveiro, Maria, Thill, Serge",September 2021,[[“That's (not) the output I expected!” On the...
20,Explaining black-box classifiers using post-ho...,"Kenny, Eoin M., Ford, Courtney, Quinn, Molly, ...",May 2021,[[Explaining black-box classifiers using post-...
21,Algorithm runtime prediction: Methods & evalua...,"Hutter, Frank, Xu, Lin, Hoos, Holger H., Leyto...",January 2014,[[Algorithm runtime prediction: Methods & eval...
22,Wrappers for feature subset selection,"Kohavi, Ron, John, George H.",December 1997,[[Wrappers for feature subset selection]]
23,Commonsense visual sensemaking for autonomous ...,"Suchan, Jakob, Bhatt, Mehul, Varadarajan, Srik...",October 2021,[[Commonsense visual sensemaking for autonomou...
24,"Quantum computation, quantum theory and AI","Ying, Mingsheng",February 2010,"[[Quantum computation, quantum theory and AI]]"